version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: nanophate-cci/gcp-e2-medium
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: whoami
      - run: cat ~/.bashrc
      - run:
          name: Check Python version
          command: source ~/.bashrc && python --version
